### ISSUE TITLE
generated icons 404

### ISSUE THREAD

**Issue by dawnerd** [firstandthird/grunt-set-rapptor#2]
/ui/icon-font 404s since icon-font lives under common. Actual path should be /ui/common/icon-font

Other thing we could do it make rapptor set /ui to common, but then /ui/_dist would break...

**Comment by jgallen23** [comment]
Balls. I knew I should have tested

**Comment by jgallen23** [comment]
Just change relative path

**Comment by dawnerd** [comment]
Fixed here: https://github.com/firstandthird/grunt-set-rapptor/commit/5453deebad0fd34b0673450948e1602bc599ef79 (Mistakenly put #1 in commit, whoops).

You'll have to npm publish though, I don't have access.
